### PR TITLE
Add $round() to Number.prototype #46

### PR DESCRIPTION
**Pull request by VladimirRybalko**
Done it.

### CODE REVIEW

**Comment by avand** [comment]
Love it. Happy to merge, but just a quick clarification. `toFixed()` returns a string, not a number. Is this what you're expecting? Maybe `deepEqual()` is obfuscating that issue.

**Comment by VladimirRybalko** [comment]
Uh. You are absolutely right. I don't know how I have missed it.

**Comment by avand** [comment]
No worries. The only time I think I'd want a string is if I wanted to pad the decimals with zeros. For example, `4.90`, which of course can be only represented as a string. Do you think it makes sense for `$round()` to take a second optional boolean argument, `pad` that uses `toFixed()` to achieve this result? Then we could do `(4.9).$round(2, true)` and get `"4.90"`.

Also, I just noticed that this issue is marked for the v2 milestone/branch but you made the change against v1 master. I can port it over later but if you're planning on taking on any other v2 issues, work against that branch.

**Comment by VladimirRybalko** [comment]
In my opinion $round operation should return a float type. It's a math operation. And it makes sense that math operation returns a number or float value. 
However I like your idea about string representation. It may be usefull for some cases. May be an addition number.prototype extension (for example $roundString()) will be a good solution instead of the second optional argument.

Also, good note about v2 branch. I will take note of this.
Thanks

**Comment by avand** [comment]
We'll sit tight on the padded string case for now. Glad we could close out an issue!

I ported this code over to v2: c9dea29a. A lot has changed in v2 so I just copy/pasted what you had done instead of merging. I think v2 is paste the point of being updated from master now. New test suite, new way of extending prototypes, etc.

Look forward for more contributions. Thanks!

**Pull request merged**
